services:
  clockwatch:
    build:
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}

  test:
    build:
      dockerfile: Dockerfile
    command: npm test
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}